# Generated by Django 5.2.12 on 2026-03-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField(db_index=True)),
            ],
            options={
                'verbose_name': 'Escrito',
                'verbose_name_plural': 'Escritos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_etapa', models.CharField(choices=[('investigacion_previa', 'Investigación Previa'), ('instruccion_fiscal', 'Instrucción Fiscal'), ('evaluacion_preparatoria', 'Evaluación y Preparatoria'), ('audiencia_preparatoria', 'Audiencia Preparatoria'), ('juicio', 'Juicio'), ('sentencia', 'Sentencia'), ('suspension_condicional', 'Suspensión Condicional')], max_length=30)),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='pendiente', max_length=10)),
            ],
            options={
                'verbose_name': 'Etapa Procesal',
                'verbose_name_plural': 'Etapas Procesales',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaDocumento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, default='', upload_to='evidencias/%Y/%m/')),
            ],
            options={
                'verbose_name': 'Evidencia / Documento',
                'verbose_name_plural': 'Evidencias / Documentos',
                'ordering': ['-titulo'],
            },
        ),
        migrations.CreateModel(
            name='ExpedienteAbogado',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Expediente — Abogado',
                'verbose_name_plural': 'Expedientes — Abogados',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='ExpedientePenal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_juicio', models.CharField(blank=True, db_index=True, max_length=100)),
                ('unidad_judicial', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('denuncia', 'Denuncia'), ('indagacion_previa', 'Indagación Previa'), ('instruccion_fiscal', 'Instrucción Fiscal'), ('evaluacion_preparatoria', 'Evaluación y Preparatoria'), ('juicio', 'Juicio'), ('sentencia', 'Sentencia'), ('archivado', 'Archivado'), ('abandonado', 'Abandonado'), ('prescrito', 'Prescrito')], db_index=True, default='denuncia', max_length=30)),
                ('fecha_apertura', models.DateField(db_index=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('prescripcion_fecha_limite', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expediente Penal',
                'verbose_name_plural': 'Expedientes Penales',
                'ordering': ['-numero_juicio'],
            },
        ),
        migrations.CreateModel(
            name='RolExpediente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rol de Expediente',
                'verbose_name_plural': 'Roles de Expediente',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RolProcesal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Rol Procesal',
                'verbose_name_plural': 'Roles Procesales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SujetoProcesal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Sujeto Procesal',
                'verbose_name_plural': 'Sujetos Procesales',
                'ordering': ['-cedula'],
            },
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('articulo_coip', models.CharField(max_length=50, unique=True, verbose_name='Artículo COIP')),
                ('accion_tipo', models.CharField(blank=True, choices=[('publica', 'Pública'), ('privada', 'Privada')], max_length=100, verbose_name='Tipo de Acción')),
                ('plazo_dias_investigacion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo Días Investigación')),
                ('plazo_instruccion_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Plazo Días Instruccion')),
            ],
            options={
                'verbose_name': 'Tipo de Delito',
                'verbose_name_plural': 'Tipos de Delito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEscrito',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de Escrito',
                'verbose_name_plural': 'Tipos de Escrito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('accion', models.CharField(blank=True, max_length=200, verbose_name='Acción')),
                ('tipo_accion', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=10, verbose_name='Tipo de Acción')),
            ],
            options={
                'verbose_name': 'Tipo de Procedimiento',
                'verbose_name_plural': 'Tipos de Procedimiento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaEvidencia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Evidencia',
                'verbose_name_plural': 'Categorías de Evidencia',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_categoriaevidencia_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='core.ciudad', verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
    ]
