# Generated by Django 5.2.12 on 2026-03-15 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('penalcode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrito',
            name='abogado',
            field=models.ForeignKey(db_column='abogado_id', on_delete=django.db.models.deletion.PROTECT, related_name='escritos', to=settings.AUTH_USER_MODEL, verbose_name='Abogado'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='etapaprocesal',
            field=models.ForeignKey(blank=True, db_column='etapaprocesal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escritos', to='penalcode.etapaprocesal', verbose_name='Etapa Procesal'),
        ),
        migrations.AddField(
            model_name='evidenciadocumento',
            name='categoria',
            field=models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='penalcode.categoriaevidencia', verbose_name='Categoría de Evidencia'),
        ),
        migrations.AddField(
            model_name='evidenciadocumento',
            name='escrito',
            field=models.ForeignKey(blank=True, db_column='escrito_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='penalcode.escrito', verbose_name='Escrito'),
        ),
        migrations.AddField(
            model_name='expedienteabogado',
            name='abogado',
            field=models.ForeignKey(db_column='abogado_id', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abogados', to=settings.AUTH_USER_MODEL, verbose_name='Abogado'),
        ),
        migrations.AddField(
            model_name='expedientepenal',
            name='abogados',
            field=models.ManyToManyField(related_name='expedientes_penales', through='penalcode.ExpedienteAbogado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expedientepenal',
            name='ciudad',
            field=models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='core.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='expedientepenal',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='expedienteabogado',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abogados', to='penalcode.expedientepenal', verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='evidenciadocumento',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='penalcode.expedientepenal', verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='etapaprocesal',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='penalcode.expedientepenal', verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='expedientepenal',
            field=models.ForeignKey(db_column='expedientepenal_id', on_delete=django.db.models.deletion.CASCADE, related_name='escritos', to='penalcode.expedientepenal', verbose_name='Expediente Penal'),
        ),
        migrations.AddIndex(
            model_name='rolexpediente',
            index=models.Index(fields=['nombre'], name='idx_rolexpediente_nombre'),
        ),
        migrations.AddField(
            model_name='expedienteabogado',
            name='rol',
            field=models.ForeignKey(db_column='rol_id', help_text='Ej: Abogado Principal, Asistente, etc.', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abogados', to='penalcode.rolexpediente', verbose_name='Rol'),
        ),
        migrations.AddIndex(
            model_name='rolprocesal',
            index=models.Index(fields=['nombre'], name='idx_rolprocesal_nombre'),
        ),
        migrations.AddField(
            model_name='sujetoprocesal',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='sujetos_procesales', to='penalcode.expedientepenal', verbose_name='Expediente'),
        ),
        migrations.AddField(
            model_name='sujetoprocesal',
            name='rolprocesal',
            field=models.ForeignKey(db_column='rol_id', on_delete=django.db.models.deletion.PROTECT, related_name='sujetos_procesales', to='penalcode.rolprocesal', verbose_name='Rol Procesal'),
        ),
        migrations.AddIndex(
            model_name='tipodelito',
            index=models.Index(fields=['nombre'], name='idx_tipodelito_nombre'),
        ),
        migrations.AddIndex(
            model_name='tipodelito',
            index=models.Index(fields=['articulo_coip'], name='idx_tipodelito_articulo_coip'),
        ),
        migrations.AddField(
            model_name='expedientepenal',
            name='tipodelito',
            field=models.ForeignKey(db_column='tipodelito_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.tipodelito', verbose_name='Tipo de Delito'),
        ),
        migrations.AddIndex(
            model_name='tipoescrito',
            index=models.Index(fields=['nombre'], name='idx_tipoescrito_nombre'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='tipo_escrito',
            field=models.ForeignKey(blank=True, db_column='tipo_escrito_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escritos', to='penalcode.tipoescrito', verbose_name='Tipo de Escrito'),
        ),
        migrations.AddIndex(
            model_name='tipoprocedimiento',
            index=models.Index(fields=['nombre'], name='idx_tipoprocedimiento_nombre'),
        ),
        migrations.AddField(
            model_name='expedientepenal',
            name='tipoprocedimiento',
            field=models.ForeignKey(db_column='tipoprocedimiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.tipoprocedimiento', verbose_name='Tipo de Procedimiento'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre'], name='idx_cliente_nombre'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['apellido'], name='idx_cliente_apellido'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cedula'], name='idx_cliente_cedula'),
        ),
        migrations.AddIndex(
            model_name='evidenciadocumento',
            index=models.Index(fields=['titulo'], name='idx_evi_doc_titulo'),
        ),
        migrations.AddIndex(
            model_name='evidenciadocumento',
            index=models.Index(fields=['expediente'], name='idx_evi_doc_exp'),
        ),
        migrations.AddIndex(
            model_name='etapaprocesal',
            index=models.Index(fields=['expediente'], name='idx_etapaprocesal_expediente'),
        ),
        migrations.AddIndex(
            model_name='etapaprocesal',
            index=models.Index(fields=['tipo_etapa'], name='idx_etapaprocesal_tipoetapa'),
        ),
        migrations.AddConstraint(
            model_name='etapaprocesal',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('expediente', 'tipo_etapa'), name='unique_etapa_activa_por_expediente'),
        ),
        migrations.AddIndex(
            model_name='expedienteabogado',
            index=models.Index(fields=['expediente'], name='idx_expabog_exp'),
        ),
        migrations.AddIndex(
            model_name='expedienteabogado',
            index=models.Index(fields=['abogado'], name='idx_expabog_abog'),
        ),
        migrations.AddConstraint(
            model_name='expedienteabogado',
            constraint=models.UniqueConstraint(fields=('expediente', 'abogado'), name='unique_expediente_abogado'),
        ),
        migrations.AddIndex(
            model_name='sujetoprocesal',
            index=models.Index(fields=['cedula'], name='idx_sujeto_procesal_cedula'),
        ),
        migrations.AddIndex(
            model_name='sujetoprocesal',
            index=models.Index(fields=['rolprocesal'], name='idx_sujeto_procesal_rol'),
        ),
        migrations.AddIndex(
            model_name='escrito',
            index=models.Index(fields=['fecha'], name='idx_escrito_fecha'),
        ),
        migrations.AddIndex(
            model_name='expedientepenal',
            index=models.Index(fields=['numero_juicio'], name='idx_expediente_numerojuicio'),
        ),
        migrations.AddIndex(
            model_name='expedientepenal',
            index=models.Index(fields=['cliente'], name='idx_expediente_cliente'),
        ),
    ]
