# Generated by Django 5.2.12 on 2026-03-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalcode', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='etapaprocesal',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('expediente', 'tipo_etapa'), name='unique_etapa_activa_por_expediente'),
        ),
    ]
