# Generated by Django 5.2.12 on 2026-03-15 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regiones',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_region_nombre')],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('region', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='core.region', verbose_name='Región')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='fecha de actualización')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Fecha y hora de eliminación (soft delete)', null=True, verbose_name='fecha de eliminación')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('provincia', models.ForeignKey(db_column='provincia_id', on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='core.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='idx_ciudad_nombre'), models.Index(fields=['provincia'], name='idx_ciudad_provincia')],
            },
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['nombre'], name='idx_provincia_nombre'),
        ),
        migrations.AddIndex(
            model_name='provincia',
            index=models.Index(fields=['region'], name='idx_provincia_region'),
        ),
    ]
