# Generated by Django 6.0.3 on 2026-03-11 22:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvidencia',
            fields=[
                ('categoriaevidencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría de Evidencia',
                'verbose_name_plural': 'Categorías de Evidencia',
                'db_table': 'categoriaevidencia',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='EtapaProcesal',
            fields=[
                ('etapaprocesal_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_etapa', models.CharField(choices=[('investigacion_previa', 'Investigación Previa'), ('instruccion_fiscal', 'Instrucción Fiscal'), ('evaluacion_preparatoria', 'Evaluación y Preparatoria'), ('audiencia_preparatoria', 'Audiencia Preparatoria'), ('juicio', 'Juicio'), ('sentencia', 'Sentencia'), ('suspension_condicional', 'Suspensión Condicional')], max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='pendiente', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etapa Procesal',
                'verbose_name_plural': 'Etapas Procesales',
                'db_table': 'etapaprocesal',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('provincia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Región',
                'verbose_name_plural': 'Regiones',
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='RolProcesal',
            fields=[
                ('rolprocesal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Rol Procesal',
                'verbose_name_plural': 'Roles Procesales',
                'db_table': 'rolprocesal',
            },
        ),
        migrations.CreateModel(
            name='TipoDelito',
            fields=[
                ('tipodelito_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('articulo_coip', models.CharField(max_length=50)),
                ('accion_tipo', models.CharField(blank=True, max_length=100)),
                ('plazo_dias_investigacion', models.PositiveIntegerField(blank=True, null=True)),
                ('plazo_instruccion_dias', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Delito',
                'verbose_name_plural': 'Tipos de Delito',
                'db_table': 'tipodelito',
            },
        ),
        migrations.CreateModel(
            name='TipoProcedimiento',
            fields=[
                ('tipoprocedimiento_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('accion', models.CharField(blank=True, max_length=200)),
                ('tipo_accion', models.CharField(choices=[('publica', 'Pública'), ('privada', 'Privada')], default='publica', max_length=10)),
            ],
            options={
                'verbose_name': 'Tipo de Procedimiento',
                'verbose_name_plural': 'Tipos de Procedimiento',
                'db_table': 'tipoprocedimiento',
            },
        ),
        migrations.CreateModel(
            name='Abogado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Abogado',
                'verbose_name_plural': 'Abogados',
                'db_table': 'abogado',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ciudad', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='penalcode.ciudad')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='Escrito',
            fields=[
                ('escrito_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_escrito', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abogado', models.ForeignKey(db_column='abogado_id', on_delete=django.db.models.deletion.PROTECT, related_name='escritos', to=settings.AUTH_USER_MODEL)),
                ('etapaprocesal', models.ForeignKey(blank=True, db_column='etapaprocesal_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escritos', to='penalcode.etapaprocesal')),
            ],
            options={
                'verbose_name': 'Escrito',
                'verbose_name_plural': 'Escritos',
                'db_table': 'escrito',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteAbogado',
            fields=[
                ('expedienteabogado_id', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(blank=True, help_text='Ej: Abogado Principal, Asistente', max_length=100)),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('abogado', models.ForeignKey(db_column='abogado_id', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abogados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expediente — Abogado',
                'verbose_name_plural': 'Expedientes — Abogados',
                'db_table': 'expedienteabogado',
            },
        ),
        migrations.CreateModel(
            name='ExpedientePenal',
            fields=[
                ('expedientepenal_id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_juicio', models.CharField(blank=True, max_length=100)),
                ('unidad_judicial', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('denuncia', 'Denuncia'), ('indagacion_previa', 'Indagación Previa'), ('instruccion_fiscal', 'Instrucción Fiscal'), ('evaluacion_preparatoria', 'Evaluación y Preparatoria'), ('juicio', 'Juicio'), ('sentencia', 'Sentencia'), ('archivado', 'Archivado'), ('abandonado', 'Abandonado'), ('prescrito', 'Prescrito')], default='denuncia', max_length=30)),
                ('fecha_apertura', models.DateField()),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('prescripcion_fecha_limite', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abogados', models.ManyToManyField(related_name='expedientes_penales', through='penalcode.ExpedienteAbogado', to=settings.AUTH_USER_MODEL)),
                ('ciudad', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.ciudad')),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.cliente')),
                ('tipodelito', models.ForeignKey(db_column='tipodelito_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.tipodelito')),
                ('tipoprocedimiento', models.ForeignKey(db_column='tipoprocedimiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='penalcode.tipoprocedimiento')),
            ],
            options={
                'verbose_name': 'Expediente Penal',
                'verbose_name_plural': 'Expedientes Penales',
                'db_table': 'expedientepenal',
            },
        ),
        migrations.AddField(
            model_name='expedienteabogado',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='expediente_abogados', to='penalcode.expedientepenal'),
        ),
        migrations.CreateModel(
            name='EvidenciaDocumento',
            fields=[
                ('evidenciadocumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='evidencias/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, db_column='categoria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='penalcode.categoriaevidencia')),
                ('escrito', models.ForeignKey(blank=True, db_column='escrito_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias', to='penalcode.escrito')),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='penalcode.expedientepenal')),
            ],
            options={
                'verbose_name': 'Evidencia / Documento',
                'verbose_name_plural': 'Evidencias / Documentos',
                'db_table': 'evidenciadocumento',
            },
        ),
        migrations.AddField(
            model_name='etapaprocesal',
            name='expediente',
            field=models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='penalcode.expedientepenal'),
        ),
        migrations.AddField(
            model_name='escrito',
            name='expedientepenal',
            field=models.ForeignKey(db_column='expedientepenal_id', on_delete=django.db.models.deletion.CASCADE, related_name='escritos', to='penalcode.expedientepenal'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(db_column='provincia_id', on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='penalcode.provincia'),
        ),
        migrations.AddField(
            model_name='provincia',
            name='region',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='penalcode.region'),
        ),
        migrations.CreateModel(
            name='SujetoProcesal',
            fields=[
                ('sujetoprocesal_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='sujetos_procesales', to='penalcode.expedientepenal')),
                ('rolprocesal', models.ForeignKey(db_column='rolprocesal_id', on_delete=django.db.models.deletion.PROTECT, related_name='sujetos', to='penalcode.rolprocesal')),
            ],
            options={
                'verbose_name': 'Sujeto Procesal',
                'verbose_name_plural': 'Sujetos Procesales',
                'db_table': 'sujetoprocesal',
            },
        ),
        migrations.AddConstraint(
            model_name='expedienteabogado',
            constraint=models.UniqueConstraint(fields=('expediente', 'abogado'), name='unique_expediente_abogado'),
        ),
        migrations.AddConstraint(
            model_name='etapaprocesal',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('expediente', 'tipo_etapa'), name='unique_etapa_activa_por_expediente'),
        ),
    ]
