# Generated by Django 5.0.2 on 2026-03-11 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penalcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abogado',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='escrito',
            name='fecha',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='etapaprocesal',
            name='fecha_inicio',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='evidenciadocumento',
            name='archivo',
            field=models.FileField(blank=True, default='', upload_to='evidencias/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='expedientepenal',
            name='estado',
            field=models.CharField(choices=[('denuncia', 'Denuncia'), ('indagacion_previa', 'Indagación Previa'), ('instruccion_fiscal', 'Instrucción Fiscal'), ('evaluacion_preparatoria', 'Evaluación y Preparatoria'), ('juicio', 'Juicio'), ('sentencia', 'Sentencia'), ('archivado', 'Archivado'), ('abandonado', 'Abandonado'), ('prescrito', 'Prescrito')], db_index=True, default='denuncia', max_length=30),
        ),
        migrations.AlterField(
            model_name='expedientepenal',
            name='fecha_apertura',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expedientepenal',
            name='numero_juicio',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sujetoprocesal',
            name='cedula',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
