# Generated by Django 5.2.12 on 2026-03-13 02:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(help_text='Correo electrónico único del usuario', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('ci', models.CharField(blank=True, help_text='Cédula de identidad única del usuario', max_length=20, null=True, unique=True, verbose_name='Cédula de Identidad')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el usuario puede iniciar sesión', verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, help_text='Indica si el usuario puede acceder al admin', verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, related_name='security_user_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='security_user_set', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['username'],
                'indexes': [models.Index(fields=['username'], name='idx_user_username'), models.Index(fields=['email'], name='idx_user_email'), models.Index(fields=['ci'], name='idx_user_ci')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
